# Generated by Django 4.2.7 on 2024-01-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
