# Generated by Django 4.2.7 on 2023-12-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_details',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='company',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_details',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
